### ISSUE TITLE
System.NotSupportedException: 'No corresponding DType value for CLR type System.Int64[]'

### ISSUE THREAD

**Issue by nandaccio** [tech-quantum/Amplifier.NET#14]
I just downloaded the latest version of the source code and, without any changes, I ran the examples from within Visual Studio 2019.

I obtain a **System.NotSupportedException: 'No corresponding DType value for CLR type System.Int64[]'** error during the kernel enumeration:
 
![2021-02-10 13_31_12-Amplifier NET (Debugging) - Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/13116598/107510923-0e61d300-6ba5-11eb-8289-001ca5803521.png)

Actually Int64 does not seem to be one of the supported types.

**Comment by nandaccio** [comment]
Issues seems limited to **SimpleKernelEx**:

1) is DType.Float32 missing from var y ?
```
            //Create variable a, b and r
            var x = new XArray(new float[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 }).Reshape(3, 3);
            var y = new XArray(new long[] { 3, 3 });
            var z = new XArray(new long[] { 3, 3 }, DType.Float32);
```

2)   exec.AddTensor(x, y, z); ==> It triggers the following error: : **'Method AddTensor not found!'**

**Comment by nandaccio** [comment]
Should I replace var y with:

var y = new XArray(new long[] { 3, 3 }, DType.Float32);

and 

.AddTensor with .AddData ?

**Comment by deepakkumar1984** [comment]
Should be fixed, added proper exception message
