### ISSUE TITLE
Not calling 'UseDevice()' causes Exceptions - (_context == null)

### ISSUE THREAD

**Issue by fraser125** [tech-quantum/Amplifier.NET#4]
There are several places and several fixes for this issue, I'm not sure the preferred approach.
The easy one:
OpenCLCompiler.Dispose()
```
  if (_context != null)
                _context.Dispose();
```
The others are much more involved.

**Comment by chetankumar** [comment]
@fraser125 : Can you post some code where the issue can be replicated?

**Comment by fraser125** [comment]
I'm very sorry, I determined GPU processing wasn't practical for my application soon after posting this. 
You can decide if this issue is worth fixing or not
```
using Amplifier;

namespace AmplifierExamples
{
    public class Issue4 : IExample
    {
        public void Execute()
        {
            using (var compiler1 = new OpenCLCompiler())
            {
            } <== Throws Exception Here.
        }
    }
}
```
FYI: I only have one device so several of your Examples crash out of the box for me. I only have a Baffin GPU in the device list.
- ArrayForLoopEx
- CompilerExecuteEx
- SaveAndLoadEx

**Comment by deepakkumar1984** [comment]
I think OpenCL doesn't support
