### ISSUE TITLE
How do I use 2dimensional Arrays?

### ISSUE THREAD

**Issue by Daniel2193** [tech-quantum/Amplifier.NET#9]
I want to use functions like

`[OpenCLKernel]
        void feedForward([Global]float[] inputs, float[,] weights, [Global]float[] outputs)
        {
            outputs[i] = inputs[j] * weights[j,i];
        }`
for my NN
How do I do that?

**Comment by kgamecarter** [comment]
You need to reduce the 2D array down into a 1D array.
[https://stackoverflow.com/questions/35442327/2d-array-as-opencl-kernel-argument](https://stackoverflow.com/questions/35442327/2d-array-as-opencl-kernel-argument)
